-- Seeder: Products data
-- Created: 2024-01-01
-- Description: Produtos iniciais para o catálogo

REPLACE INTO products (
    name, slug, description, full_description, category, price_per_m3, 
    applications, image_url, gallery, certifications, specifications, 
    availability, origin_location, supplier, is_active, is_featured
) VALUES
(
    'Pinus Tratado',
    'pinus-tratado',
    'Madeira de pinus tratada em autoclave, ideal para estruturas.',
    'Madeira de pinus tratada em autoclave com CCA (Arseniato de Cobre Cromatado), oferecendo proteção contra fungos, brocas e cupins. Ideal para estruturas, telhados e construções em geral.',
    'estrutural',
    450.00,
    '["estruturas", "telhados", "andaimes"]',
    'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=treated%20pine%20lumber%20stack%20construction%20grade%20wood%20planks%20professional%20photography&image_size=square_hd',
    '["https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=treated%20pine%20lumber%20close%20up%20texture%20wood%20grain&image_size=landscape_4_3", "https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=pine%20wood%20construction%20site%20framing%20structure&image_size=landscape_4_3"]',
    '["FSC", "IBAMA"]',
    '{"Densidade": "450-550 kg/m³", "Umidade": "15-18%", "Tratamento": "CCA em autoclave", "Dimensões": "Padrão e sob medida"}',
    'in_stock',
    'Região Sul do Brasil',
    'Madeiras do Sul Ltda',
    1,
    1
),
(
    'Eucalipto Tratado',
    'eucalipto-tratado',
    'Eucalipto tratado para estruturas e paisagismo.',
    'Madeira de eucalipto tratada com preservantes, ideal para mourões, postes e estruturas externas. Excelente resistência à umidade e pragas.',
    'estrutural',
    380.00,
    '["mouroes", "postes", "estruturas_externas"]',
    'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=treated%20eucalyptus%20lumber%20posts%20outdoor%20construction%20professional%20photography&image_size=square_hd',
    '["https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=eucalyptus%20wood%20texture%20grain%20pattern&image_size=landscape_4_3", "https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=eucalyptus%20fence%20posts%20installation&image_size=landscape_4_3"]',
    '["FSC", "CERFLOR"]',
    '{"Densidade": "600-800 kg/m³", "Umidade": "12-15%", "Tratamento": "Preservante CCA", "Dimensões": "Padrão"}',
    'in_stock',
    'Interior de São Paulo',
    'Eucalipto Premium',
    1,
    0
),
(
    'Ipê para Deck',
    'ipe-deck',
    'Ipê premium para decks e pisos externos.',
    'Madeira de ipê de primeira qualidade, conhecida por sua excepcional durabilidade e resistência. Ideal para decks, pisos externos e estruturas que exigem máxima resistência às intempéries.',
    'deck',
    1200.00,
    '["decks", "pisos_externos", "estruturas_pesadas"]',
    'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=ipe%20hardwood%20deck%20planks%20premium%20tropical%20lumber%20professional%20photography&image_size=square_hd',
    '["https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=ipe%20wood%20deck%20installation%20luxury%20outdoor&image_size=landscape_4_3", "https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=ipe%20wood%20grain%20texture%20close%20up%20premium%20quality&image_size=landscape_4_3"]',
    '["FSC", "IBAMA", "CITES"]',
    '{"Densidade": "950-1200 kg/m³", "Umidade": "8-12%", "Durabilidade": "Classe I (muito alta)", "Dimensões": "Sob medida"}',
    'on_demand',
    'Amazônia Legal',
    'Madeiras Amazônicas Certificadas',
    1,
    1
),
(
    'Cumaru',
    'cumaru',
    'Cumaru, alternativa premium ao ipê.',
    'Madeira de cumaru de alta qualidade, conhecida por sua durabilidade e resistência. Excelente alternativa ao ipê com ótima relação custo-benefício.',
    'deck',
    950.00,
    '["decks", "estruturas_pesadas", "pisos"]',
    'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=cumaru%20hardwood%20planks%20premium%20tropical%20lumber%20professional%20photography&image_size=square_hd',
    '["https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=cumaru%20wood%20deck%20installation%20outdoor%20construction&image_size=landscape_4_3", "https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=cumaru%20wood%20texture%20grain%20pattern%20close%20up&image_size=landscape_4_3"]',
    '["FSC", "IBAMA"]',
    '{"Densidade": "850-1000 kg/m³", "Umidade": "8-12%", "Durabilidade": "Classe I (muito alta)", "Dimensões": "Padrão e sob medida"}',
    'in_stock',
    'Pará',
    'Madeiras do Norte',
    1,
    0
),
(
    'Jatobá',
    'jatoba',
    'Jatobá, madeira nobre para acabamentos.',
    'Madeira de jatobá com coloração avermelhada característica. Muito utilizada em pisos, móveis e acabamentos de alto padrão. Excelente trabalhabilidade.',
    'acabamento',
    800.00,
    '["pisos", "moveis", "acabamentos"]',
    'https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=jatoba%20hardwood%20flooring%20planks%20reddish%20brown%20wood%20professional%20photography&image_size=square_hd',
    '["https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=jatoba%20wood%20flooring%20installation%20interior%20luxury&image_size=landscape_4_3", "https://trae-api-us.mchost.guru/api/ide/v1/text_to_image?prompt=jatoba%20wood%20grain%20reddish%20color%20texture%20detail&image_size=landscape_4_3"]',
    '["FSC", "IBAMA"]',
    '{"Densidade": "750-900 kg/m³", "Umidade": "8-12%", "Cor": "Avermelhada", "Dimensões": "Padrão e sob medida"}',
    'in_stock',
    'Mato Grosso',
    'Madeiras Exóticas Brasil',
    1,
    0
);